Update commiter's e-mail
When using private email, Git throws
```
error: GH007: Your push would publish a private email address.
```
during `git push`.
We need to make commits using a noreply e-mail (or change GH's 'Keep my email
address private' setting).